### ISSUE TITLE
JSON pretty bug

### ISSUE THREAD

**Issue by laoshanxi** [laoshanxi/app-mesh#135]
Issue: "docker_image" should in a new line.

(base) root@appmesh:~/code/app-mesh/build# appc reg -n docker -c 'sh -c "exit 5"' -d centos:7 -f
{
  "behavior": {
    "exit": "standby"
  },
  "command": "sh -c \"exit 5\"","docker_image": "centos:7",
  "name": "docker",
  "owner": "admin",
  "register_time": "2021-09-25T12:10:20+08",
  "retention": "10",
  "status": 1
}

Position:
https://github.com/laoshanxi/app-mesh/blob/main/src/common/Utility.cpp#L651
std::string Utility::prettyJson(const std::string &jsonStr)

**Comment by HanixNicolas** [comment]
<pre>
    std::string json = R"({"behavior":{"exit":"standby"},"command":"sh -c "exit5"","docker_image":"centos:7","name":"docker","owner":"admin","register_time":"2021-09-25T12:10:20+08","retention":"10","status":1})";
    std::string xxjson = prettyJson(json);
    std::cout << "json:\n" << xxjson << std::endl;
</code>


Test with the above code, it seems prettyJson work well. The root cause should be in the other level. 
![99](https://user-images.githubusercontent.com/35907136/134799899-165ddd7e-13b8-4187-adab-77c5df7ce535.png)
